#!/usr/bin/env bash

set -eu

rundir="$(dirname $(readlink -f $0))"
. ${rundir}/helpers/useful.sh

work_dir=${PWD}
image_name="magthe/hfa-builder"
shell=no
owner_uid=$(id -u)
owner_gid=$(id -g)

usage() {
    cat << EOF
Usage: makeahpkg [options] -- [packages]

Run this script in your HFA dir to build the named packages.

Options:
-h          This help
-u          User to own the built files
-g          Group to own the built files
-b <dir>    Location of your HFA folder (default: .)
-s          Enter a shell instead of building
EOF
exit 0
}

while getopts hu:g:a:s opt; do
    case "${opt}" in
        h) usage; exit 0;;
        u) owner_uid=${OPTARG};;
        g) owner_gid=${OPTARG};;
        s) shell=yes;;
    esac
done
shift $((OPTIND - 1))

if [[ "x${shell}" == "xno" ]]; then
    docker_cmd="/usr/bin/bash /hfa/helpers/buildpkgs -u ${owner_uid} -g ${owner_gid} -b /hfa -- $*"
else
    docker_cmd="/usr/bin/bash -l"
fi

docker run -i -t -v=${work_dir}:/hfa -u hfa --env-file /etc/environment \
    -v /home/magnus/Dropbox/archrepo:/mtrepo \
    ${image_name}:latest \
    ${docker_cmd}
