version: 2
jobs:
  build:
    docker:
      - image: magthe/hfa-builder:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Fix repo-add
          command: |
            sudo patch /usr/bin/repo-add helpers/repo-add.patch

      - run:
          name: Build packages
          command: |
            ./helpers/buildpkgs \
              cabal-install stack \
              pandoc pandoc-citeproc pandoc-crossref \
              hlint stylish-haskell shelltestrunner \
              hpack alex happy

      - run:
          name: List repo folder
          command: |
            ls -lah /repo

      - run:
          name: Build archive
          command: |
            (cd /repo; tar --create --file ${HOME}/repo/hfa-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}.tar.xz --xz *.xz)
            ln -s hfa-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}.tar.xz packages.tar.xz

      # It's not possible to use envvars in `store_artifacts`, keep an eye on
      # the ticket:
      # https://discuss.circleci.com/t/can-i-use-environment-variables-in-store-artifacts/11226
      - store_artifacts:
          path: packages.tar.xz

      # - store_artifacts:
      #     path: hfa-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}.tar.xz
