resolver: lts-14.21

packages:
  - '.'

extra-deps:
  - roman-numerals-0.5.1.5
  - HsYAML-0.2.0.0
  - HsYAML-aeson-0.2.0.0
  - doclayout-0.2.0.1
  - doctemplates-0.8
  - emojis-0.1
  - haddock-library-1.8.0
  - jira-wiki-markup-1.0.0
  - pandoc-2.9.1.1
  - pandoc-types-1.20
  - regex-pcre-builtin-0.95.0.8.8.35
  - skylighting-0.8.3
  - skylighting-core-0.8.3
  - texmath-0.12


flags: {}

extra-package-dbs: []
