resolver: lts-12.21

packages:
  - '.'

extra-deps:
  - HsYAML-0.1.1.2
  - haddock-library-1.7.0
  - hslua-1.0.1
  - hslua-module-text-0.2.0
  - pandoc-2.4
  - roman-numerals-0.5.1.5

flags: {}

extra-package-dbs: []
