resolver: lts-9.13

packages:
  - '.'

extra-deps:
  - cmark-gfm-0.1.3
  - doctemplates-0.2.1
  - hslua-0.9.5.1
  - hslua-module-text-0.1.2.1
  - pandoc-2.0.6
  - pandoc-types-1.17.3.1
  - roman-numerals-0.5.1.5
  - skylighting-0.5.1
  - syb-0.6
  - tagsoup-0.14.6
  - texmath-0.10.1.1

flags: {}

extra-package-dbs: []
